from __future__ import annotations

from dataclasses import dataclass


ERROR_CODES = frozenset({
    "INVALID_ARGUMENT", "NOT_FOUND", "SUBJECT_UNAVAILABLE", "AUTHORITY_DRIFT",
    "GENERATION_MISMATCH", "RELEASE_MISMATCH", "HASH_MISMATCH",
    "SOURCE_CHANGED_DURING_READ", "SQLITE_BUSY", "SQLITE_CORRUPT",
    "OUTPUT_LIMIT", "TIMEOUT", "INTERNAL_SAFE", "ROUTE_CONTEXT_REQUIRED",
    "ROUTE_SCOPE_MISMATCH", "PROJECTION_EVENT_MISMATCH",
    "PROJECTION_MANIFEST_MISMATCH", "RECORD_TOO_LARGE",
    "READ_SESSION_REQUIRED", "READ_SESSION_UNSAFE", "READ_SESSION_INVALID",
    "READ_SESSION_SUBJECT_MISMATCH", "READ_SESSION_PROFILE_MISMATCH",
    "CURSOR_INVALID", "CURSOR_SESSION_MISMATCH",
    "CAPTURE_BINDING_REQUIRED", "CAPTURE_MANIFEST_INVALID",
    "CAPTURE_SUBJECT_MISMATCH", "ARTIFACT_NOT_BOUND",
    "ARTIFACT_HASH_MISMATCH", "ARTIFACT_TOO_LARGE",
    "ARTIFACT_MEDIA_UNSUPPORTED",
    "SNAPSHOT_PATH_ESCAPE", "SNAPSHOT_SOURCE_UNSAFE", "SNAPSHOT_TOO_LARGE",
    "SNAPSHOT_BLOB_INVALID", "SNAPSHOT_REOPEN_MISMATCH",
    "AUTHORITY_SNAPSHOT_REQUIRED",
    "PREFLIGHT_READ_ROOT_INVALID", "PREFLIGHT_TOOL_POLICY_INVALID",
    "PREFLIGHT_SESSION_INVALID", "PREFLIGHT_SUBJECT_MISMATCH",
    "PREFLIGHT_RELEASE_BINDING_MISMATCH", "PREFLIGHT_SESSION_REQUIRED",
    "PREFLIGHT_CENTRAL_RELEASE_UNAVAILABLE",
    "PREFLIGHT_CENTRAL_BINDING_MISMATCH",
})


@dataclass(slots=True)
class StudyReadError(Exception):
    code: str
    message: str
    retryable: bool = False

    def __post_init__(self) -> None:
        if self.code not in ERROR_CODES:
            raise ValueError(f"unknown safe error code: {self.code}")
        Exception.__init__(self, self.message)
